### ISSUE TITLE
Why am I here?

### ISSUE THREAD

**Issue by Rochet2** [tkrokli/TrinityCore#16]
title says it all : )
Why am I / we here?

**Comment by tkrokli** [comment]
Oh. I was planning on forking something from your repo and I thought it would be practical to give you access in case I was going to create a Pull Request where outside help would be useful.

Perhaps this is too soon, that I should only do this per Pull Request and not in general?

**Comment by Rochet2** [comment]
Mm. alright.

**Comment by tkrokli** [comment]
"alright" meaning 'remove me', or 'leave it as it is' ?

**Comment by Rochet2** [comment]
meaning fine as is.
