### ISSUE TITLE
Quest - The Drakkensryd - Quest ID 12886

### ISSUE THREAD

**Issue by ceresia** [tkrokli/TrinityCore#6]
TrinityCore Rev. 3761d24 2015-04-21 13:26:30 +0200 (3.3.5 branch) (Win64, Release)

Upon using the harpoon to get onto the moving "Hyldsmeet Proto-Drake" dragons you cannot move once on the dragons, and most of the time you are too far from the drakerider to attack them.

After a few attempts we were able to attack one of the drakeriders but once they are low on health they fall off the dragon and float in the air, making it impossible to kill them.

Also upon using the harpoon on the "Column Ornament" to get back on the platform places the character into the ground.  The character is in combat still and stuck in the ground, unable to move or log out.

This is an important quest as it will send you to the "Sons of Hodir" to start questing.

**Comment by ceresia** [comment]
Further testing:

Using harpoon on the "Column Ornament" acts as a vehicle, you are stuck in the ground and need to activate your vehicle bar and eject yourself from the vehicle, moving you roughly 10FT in the air.

Before I eject it looks like this, some players do not have their vehicle bar enabled or they do not notice the small eject vehicle icon:

![eject](https://scontent-ord.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11206081_10206313958066055_6773319098472712654_n.jpg?oh=ac926e72702082e63c50d5e0d65f2ca6&oe=55D52012)


A lot of points in the quest, including sitting on a dragon, the game thinks I am falling, causing me to be in a state of parachute, perhaps this causes the issues with not being able to attack sometimes:

![parachute](https://scontent-ord.xx.fbcdn.net/hphotos-xpa1/v/t1.0-9/11206050_10206313957906051_8936437280236183642_n.jpg?oh=9465dc61d89057fceeca5949ec55c2ee&oe=559CEB66)

Here is a screenie of me on the dragon, in limbo with the parachute still, targeting the rider, unable to attack, too far away...

![too far](https://scontent-ord.xx.fbcdn.net/hphotos-xtf1/t31.0-8/10498565_10206313958186058_1301800936454859713_o.jpg)

**Comment by ceresia** [comment]
Further investigation, I was able to kill one with a HUGE finishing move from my rogue, but it did not give me any credit...

:)

**Comment by tkrokli** [comment]
Thanks for the feedback, although this is already one of the older issues present in TrinityCore source:

**[[QUEST] The Drakkensryd](https://github.com/TrinityCore/TrinityCore/issues/1350) #1350**
https://github.com/TrinityCore/TrinityCore/issues/1350

**Comment by ceresia** [comment]
I noticed the quest already in the trinitycore source, didn't know if I should 1: add it here also, but 2: add screenshots and another explanation of the issue.

Happy hunting!

**Comment by tkrokli** [comment]
Looking at the last screenshot, it strikes me that your are not transformed into a Hyldnir battlemaiden. Maybe there is something wrong with the aura or the quest to get that transformation from the Crone in one of the earlier quests?
