### ISSUE TITLE
Minigob Manabok

### ISSUE THREAD

**Issue by ceresia** [tkrokli/TrinityCore#7]
Firstly, I never remember being "manabonked" in retail, the years and years I played and utilized Dalaran, but that's not the real issue, he is just annoying.

The issue is that if I log my toon out in Dalaran I get mail that contains:

http://www.wowhead.com/item=44817/the-mischief-maker

I get 2-10 of these depending on how long I have logged out for, I would call this a bug, because he sends it to you after he manabonks you, so I would only assume he is manabonking my logged out character.

**Comment by GalaxyWoW** [comment]
he is really annoying... 10 minutes in Dalaran and 10 unread mails from that guy...

**Comment by ceresia** [comment]
I created a macro with a GM that is literally just  ".die"

I wait for manabonk with my GM character with auto-targeting on, and once he targets me and sheeps me I kill him
then I do:
.npc delete

Then he is good as gone until the next release :)

**Comment by tkrokli** [comment]
Haha, I love the workaround, especially the description of how you lay in wait to ambush him. Perhaps I should delete him from my next release? :stuck_out_tongue_winking_eye:
