### ISSUE TITLE
Unattainable Quests in Azuremyst Isle

### ISSUE THREAD

**Issue by Laonefaye** [tkrokli/TrinityCore#9]
My draenei character is unable to accept quests. The quest box and text appear, but when trying to accept, the text box disappears and nothing happens. The quests must be manually added via gm commands. So far, the affected quests include:
9279 - You Survived!
9280 - Replenishing the Healing Crystals
9409 - Urgent Delivery!
9283 - Rescue the Survivors!
9371 - Botanist Taerix
10302 - Volatile Mutations

This is as far as I've gotten, but as every single quest has been like this so far, I'm assuming that the others are affected as well. I have not had trouble so far in completing the quests, though.

**Comment by tkrokli** [comment]
Hmm, I thought this was denied by DeadZone and not a real issue? I am going to test it, but I haven't heard that anyone else has had this issue. Are you sure you haven't changed something in the database or added material from elsewhere? BTW: is this on release 1.4, 1.3, 1.2, 1.1 or 1.0? (**important info**)

**Comment by Laonefaye** [comment]
I haven't changed a thing in the database or anywhere else, because I wouldn't know how to even if I wanted to. It's whichever one is the latest release. I had to do a clean reinstall of my computer's OS a few months ago, and just re-installed Jeutie's repack about a month and a half or so ago.

**Comment by tkrokli** [comment]
The repack control panel hasn't got anything to do with the release. It has always been 1.1 as I can remember. If you are using my release 1.4 then the core revision hash is https://github.com/tkrokli/TrinityCore/commit/3761d24 <= link

**Comment by Laonefaye** [comment]
Oh, okay. I didn't know where to look to find that. That link led me to a language I do not speak. <__<

**Comment by Laonefaye** [comment]
I like using repacks because I don't know programming. At all. I have never used SQL, and don't know my way around databases, unless they are in Excel. All I did, this time and last, was:
1. Download repack and other required files (dbc, maps, mmaps, vmaps)
2. Follow instructions (basically, put everything into the Core folder)
3. Play game. 

I have no explanation for why these problems have arisen this time.

**Comment by tkrokli** [comment]
OK, fair enough. I will release a new edition soon, let us see if that one has got working quests or not.

**Comment by Laonefaye** [comment]
Sorry I couldn't be more helpful. :/

**Comment by tkrokli** [comment]
Hang on, I want to confirm this before I close this issue. Leave it open for now and let us see. I just haven't had time to test it myself, since I am too busy packing files and preparing uploads and a new post.

**Comment by ceresia** [comment]
I know heavily in Azuremyst Isle that when you talk to the NPC, the quest is automatically accepted, but the quest text box doesn't go away so it gives the illusion you "cannot" accept it, although it already has technically been auto accepted.  Other than that is this a GM account?  Have you tried another character or another class?  

Is this ONLY for a Draenei?

**Comment by tkrokli** [comment]
Good point, I used to have a lot of that in the orc starting area with the level 1-5 (auto accept) quests. I am not sure if it has gone away entirely, but I can test it again now that I have released a new version - TrinityCore rev. 5ef9f1415ad9 2015-04-29 23:16:12 +0100 (3.3.5 branch) (Win64, Release) /
TrinityCore rev. 5ef9f1415ad9 2015-04-29 23:16:12 +0100 (3.3.5 branch) (Win32, Release)

**Comment by Laonefaye** [comment]
Oops! Okay.
Ceresia, the quests aren't accepted at all. I checked my quest log after many attempts to accept these quests, but the log remained empty. So far I've started a human paladin, gnome mage, and dwarf hunter without this issue. I can try starting a blood elf to see if it's BC-related.

**Comment by tkrokli** [comment]
OK, I may find some time to test this one tonight as well as Ceresia's Group/Party Quest Loot issue #4 .

**Comment by Laonefaye** [comment]
Nupe, same exact thing happened to a BE character.

**Comment by tkrokli** [comment]
What is the name and/or ID of the Quest(s) you found to be not working on the BE character?

**Comment by Laonefaye** [comment]
I just tried the first one, Reclaiming Sunstrider Isle (8325), and assume that the rest will be the same. I've encountered an additional problem with the starting quests acting this way. I was playing on my draenei character, and when I reached the part when I'm supposed to get a quest from an item (Blood Elf Plans - 9798, dropped by Surveyor Candress - 16522), I cannot accept the quest at all. When I tried by using the .lookup quest and .quest add commands, as I'd been doing for the previous quests, I received the following error message: "Quest 9798 started from item. For correct work, please, add item to inventory and start quest in normal way: .additem 24414". Since I already have the item in my inventory, I'm not sure if I'll be able to accept this quest at all. 

One last oddity with unattainable quests: while my dwarf and gnome characters were both able to accept and complete their starting quests normally, when I took my level 30 human character to that area to complete the quests (aiming for the Loremaster achievement), they acted in the same problematic manner; not letting me accept unless I forced them manually with commands.

**Comment by tkrokli** [comment]
I find this very different from what I am seeing in my game client and my copy of the repack. I have never seen this problem myself, only when trying to share quests with other players. Not direct quest pickup.

**Comment by Laonefaye** [comment]
I'm so confused. I don't know what's causing this problem, nor how to fix it. And as I've invested some time in my main already, I'm not keen on starting over again. I already had to do that once when something went sideways, and I had a 60 then. :/

**Comment by tkrokli** [comment]
Just make a backup of your **auth** and **characters** databases, so you can keep all your characters for later, even if you reinstall the repack or upgrade to a newer repack. Also, keep a copy of that backup somewhere else than in/on your computer, in case anything should happen to your current repack setup.

**Comment by Laonefaye** [comment]
<facepalm> how do i do that...

**Comment by tkrokli** [comment]
You need an editor like HeidiSQL or SQLyog Community (choose the one you like best), then use the built-in functionality in that program to save the contents from 'auth' and 'characters' to separate files.

Please also post about this in the forum, because these pages is more about fixing a known issue.

**Comment by Laonefaye** [comment]
Augh. I have so little experience with any of those programs, I don't know how to do what you're suggesting. I have HeidiSQL, and the whole thing looks like gobbledegook. :(  I will post in the forum.
